# Generated by Django 2.2.6 on 2019-10-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20191003_0724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
